# Generated by Django 6.0.4 on 2026-04-17 13:59

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="time_zone",
            field=models.CharField(
                default="UTC",
                max_length=64,
                validators=[users.validators.validate_time_zone],
                verbose_name="Часовой пояс",
            ),
        ),
    ]
