# Generated by Django 6.0.4 on 2026-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="care_notifications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Получать ежедневные уведомления в Telegram.",
                verbose_name="Уведомления об уходе",
            ),
        ),
    ]
