# Generated by Django 6.0.4 on 2026-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_care_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telegram_link_token",
            field=models.CharField(
                blank=True,
                help_text="Одноразовый токен для привязки Telegram через бота.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Токен привязки Telegram",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram_link_token_created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время создания токена привязки Telegram"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram_linked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время привязки Telegram"),
        ),
    ]
