# Generated by Django 6.0.4 on 2026-04-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_telegram_link_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_care_notification_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата последнего уведомления об уходе"),
        ),
    ]
