# Generated by Django 6.0.4 on 2026-04-20 13:38

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_last_care_notification_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/avatars/",
                validators=[users.validators.validate_image_file],
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator(message="Введите корректный email.")],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                max_length=150, validators=[users.validators.validate_person_name], verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, validators=[users.validators.validate_person_name], verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, validators=[users.validators.validate_phone_number], verbose_name="Телефон"
            ),
        ),
    ]
