# Generated by Django 6.0.4 on 2026-04-17 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Имя животного")),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("snake", "Змея"),
                            ("lizard", "Ящерица"),
                            ("turtle", "Черепаха"),
                            ("frog", "Лягушка"),
                            ("spider", "Паук"),
                            ("scorpion", "Скорпион"),
                            ("other", "Иное"),
                        ],
                        max_length=20,
                        verbose_name="Тип животного",
                    ),
                ),
                (
                    "species_name",
                    models.CharField(help_text="Например: Маисовый полоз", max_length=150, verbose_name="Вид"),
                ),
                ("morph", models.CharField(blank=True, max_length=150, verbose_name="Морфа / окрас")),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Самец"), ("female", "Самка"), ("unknown", "Неизвестен")],
                        default="unknown",
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="Дата рождения")),
                (
                    "acquired_date",
                    models.DateField(
                        blank=True,
                        help_text="Укажите, когда животное появилось у вас",
                        null=True,
                        verbose_name="Дата начала владения",
                    ),
                ),
                ("weight_grams", models.PositiveIntegerField(blank=True, null=True, verbose_name="Вес (г)")),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Длина (см)"
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="pets/photos/", verbose_name="Фото")),
                ("notes", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("archived", "В архиве"),
                            ("deceased", "Умер"),
                            ("rehomed", "Передан"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "питомец",
                "verbose_name_plural": "питомцы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("feeding", "Кормление"),
                            ("measurement", "Измерение"),
                            ("cleaning", "Уборка"),
                            ("shedding", "Линька"),
                            ("custom", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип события",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, verbose_name="Название события")),
                ("event_datetime", models.DateTimeField(verbose_name="Дата и время события")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "repeat_after_days",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Повторить через (дней)"),
                ),
                (
                    "no_handling_days",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Нельзя трогать (суток)"),
                ),
                ("weight_grams", models.PositiveIntegerField(blank=True, null=True, verbose_name="Вес (г)")),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Длина (см)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="pets.pet",
                        verbose_name="Животное",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие",
                "verbose_name_plural": "события",
                "ordering": ["-created_at"],
            },
        ),
    ]
