# Generated by Django 6.0.4 on 2026-04-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="feeding_notes",
            field=models.TextField(
                blank=True,
                help_text="Например: мышь-голыш, крысёныш, сверчки, тараканы, овощная смесь",
                verbose_name="Чем кормить",
            ),
        ),
    ]
