# Generated by Django 6.0.4 on 2026-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_pet_feeding_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="length_cm",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Длина (см)"),
        ),
    ]
