# Generated by Django 6.0.4 on 2026-04-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_alter_pet_length_cm"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, карточка будет виднана главной странице и авторизованным пользователям",
                verbose_name="Показывать питомца всем",
            ),
        ),
    ]
