# Generated by Django 6.0.4 on 2026-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_pet_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, карточка будет видна на главной странице и авторизованным пользователям",
                verbose_name="Показывать питомца всем",
            ),
        ),
    ]
