# Generated by Django 6.0.4 on 2026-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0005_alter_pet_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="length_cm",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Длина (см)"),
        ),
    ]
