# Generated by Django 6.0.4 on 2026-04-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_alter_event_length_cm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Если включено, карточка будет видна на главной странице и авторизованным пользователям",
                verbose_name="Показывать питомца всем",
            ),
        ),
    ]
