# Generated by Django 6.0.4 on 2026-04-20 13:38

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0007_alter_pet_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="length_cm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="Длина (см)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="no_handling_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(365)],
                verbose_name="Нельзя трогать (суток)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="repeat_after_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3650),
                ],
                verbose_name="Повторить через (дней)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="weight_grams",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200000),
                ],
                verbose_name="Вес (г)",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="length_cm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="Длина (см)",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pets/photos/",
                validators=[users.validators.validate_image_file],
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="weight_grams",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200000),
                ],
                verbose_name="Вес (г)",
            ),
        ),
    ]
